/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeaIdRouteImport } from './routes/idea.$id'
import { Route as FounderIdRouteImport } from './routes/founder.$id'
import { Route as CompanyIdRouteImport } from './routes/company.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdRoute = IdeaIdRouteImport.update({
  id: '/idea/$id',
  path: '/idea/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIdRoute = FounderIdRouteImport.update({
  id: '/founder/$id',
  path: '/founder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdRoute = CompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company/$id': typeof CompanyIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company/$id': typeof CompanyIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company/$id': typeof CompanyIdRoute
  '/founder/$id': typeof FounderIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/company/$id' | '/founder/$id' | '/idea/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company/$id' | '/founder/$id' | '/idea/$id'
  id: '__root__' | '/' | '/company/$id' | '/founder/$id' | '/idea/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyIdRoute: typeof CompanyIdRoute
  FounderIdRoute: typeof FounderIdRoute
  IdeaIdRoute: typeof IdeaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$id': {
      id: '/idea/$id'
      path: '/idea/$id'
      fullPath: '/idea/$id'
      preLoaderRoute: typeof IdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/$id': {
      id: '/founder/$id'
      path: '/founder/$id'
      fullPath: '/founder/$id'
      preLoaderRoute: typeof FounderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id': {
      id: '/company/$id'
      path: '/company/$id'
      fullPath: '/company/$id'
      preLoaderRoute: typeof CompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyIdRoute: CompanyIdRoute,
  FounderIdRoute: FounderIdRoute,
  IdeaIdRoute: IdeaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
